// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Url struct {
	ID          uuid.UUID
	OriginalUrl string
	HashedUrl   string
	CreatedAt   time.Time
	Ttl         time.Time
}
